# Generated by Django 4.1.3 on 2022-11-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_alter_category_description_alter_category_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='middlename',
        ),
        migrations.AlterField(
            model_name='employees',
            name='status',
            field=models.CharField(max_length=100),
        ),
    ]
