# Generated by Django 4.1.3 on 2022-11-03 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0008_rename_firstname_employees_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='fullname',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='employees',
            name='lastname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employees',
            name='middlename',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
