# Generated by Django 4.1.3 on 2022-11-03 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_rename_fullname_employees_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='firstname',
            new_name='fullname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='middlename',
        ),
    ]
